Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)

In [2]:
import numpy as np

# Create two 3x3 matrices with random values
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Calculate the product of the elements in the matrices
product = np.prod(matrix1)

# Perform matrix multiplication
multiplication = np.matmul(matrix1, matrix2)

# Perform dot product
dot_product = np.dot(matrix1, matrix2)

# Print the matrices and the results of the operations
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nProduct of elements in Matrix 1:", product)
print("\nMatrix multiplication:\n", multiplication)
print("\nDot product:\n", dot_product)

Matrix 1:
 [[0.6192163  0.70397237 0.09387977]
 [0.08337886 0.98724613 0.4177578 ]
 [0.32569517 0.0299235  0.47146205]]

Matrix 2:
 [[0.51623985 0.0135481  0.57474822]
 [0.56726744 0.28202339 0.99042754]
 [0.49994003 0.64941796 0.19859709]]

Product of elements in Matrix 1: 6.466159495196907e-06

Matrix multiplication:
 [[0.76593898 0.26789309 1.07177134]
 [0.81192992 0.55085555 1.1086831 ]
 [0.4208142  0.3190276  0.31046077]]

Dot product:
 [[0.76593898 0.26789309 1.07177134]
 [0.81192992 0.55085555 1.1086831 ]
 [0.4208142  0.3190276  0.31046077]]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR

In [22]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Perform set operations
union = np.union1d(array1, array2)
intersection = np.intersect1d(array1, array2)
set_difference = np.setdiff1d(array1, array2)
xor = np.setxor1d(array1, array2)

# Print the results
print("Array 1:", array1)
print("Array 2:", array2)
print("Union:", union)
print("Intersection:", intersection)
print("Set difference (Array 1 - Array 2):", set_difference)
print("XOR:", xor)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Union: [1 2 3 4 5 6 7 8]
Intersection: [4 5]
Set difference (Array 1 - Array 2): [1 2 3]
XOR: [1 2 3 6 7 8]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array

In [3]:
import numpy as np

# Create a 1D array with random values
array = np.random.rand(10)

# Calculate the cumulative sum of the elements in the array
cumulative_sum = np.cumsum(array)

# Calculate the cumulative product of the elements in the array
cumulative_product = np.cumprod(array)

# Calculate the discrete difference of the elements in the array with n=3
discrete_diff = np.diff(array, n=3)

# Find the unique elements in the array
unique_elements = np.unique(array)

# Print the array and the results of the operations
print("Array:", array)
print("\nCumulative sum:", cumulative_sum)
print("\nCumulative product:", cumulative_product)
print("\nDiscrete difference (n=3):", discrete_diff)
print("\nUnique elements:", unique_elements)

Array: [0.71895179 0.61350885 0.36831482 0.1865553  0.30386635 0.38375745
 0.16084479 0.6122051  0.38007211 0.37551538]

Cumulative sum: [0.71895179 1.33246063 1.70077545 1.88733075 2.1911971  2.57495455
 2.73579934 3.34800444 3.72807655 4.10359193]

Cumulative product: [7.18951785e-01 4.41083281e-01 1.62457510e-01 3.03073094e-02
 9.20937147e-03 3.53416488e-03 5.68451996e-04 3.48009211e-04
 1.32268597e-04 4.96688920e-05]

Discrete difference (n=3): [ 0.20318559  0.23563607 -0.33649053 -0.2653838   0.97707673 -1.35776627
  0.91106955]

Unique elements: [0.16084479 0.1865553  0.30386635 0.36831482 0.37551538 0.38007211
 0.38375745 0.6122051  0.61350885 0.71895179]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [4]:
import numpy as np

# Create two 1D arrays with random values
array1 = np.random.rand(5)
array2 = np.random.rand(5)

# Perform addition using zip() and list comprehension
zip_addition = np.array([x + y for x, y in zip(array1, array2)])

# Perform addition using numpy.add()
numpy_addition = np.add(array1, array2)

# Create a user-defined function for addition
def add(x, y):
    return x + y

# Create a ufunc from the user-defined function
ufunc_add = np.frompyfunc(add, 2, 1)

# Perform addition using the ufunc
ufunc_addition = ufunc_add(array1, array2)

# Print the arrays and the results of the addition
print("Array 1:", array1)
print("\nArray 2:", array2)
print("\nAddition using zip() and list comprehension:", zip_addition)
print("\nAddition using numpy.add():", numpy_addition)
print("\nAddition using ufunc:", ufunc_addition)

Array 1: [0.62054021 0.80978913 0.01067209 0.35748528 0.69666524]

Array 2: [0.0083894  0.16803563 0.68069479 0.11151639 0.79576651]

Addition using zip() and list comprehension: [0.62892962 0.97782476 0.69136688 0.46900167 1.49243174]

Addition using numpy.add(): [0.62892962 0.97782476 0.69136688 0.46900167 1.49243174]

Addition using ufunc: [0.6289296176895565 0.9778247578145687 0.6913668805610449
 0.4690016659825742 1.4924317444856323]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [19]:
import numpy as np
import functools

# Define a function to calculate the LCM of two numbers
def lcm(a, b):
    return (a * b) // np.gcd(a, b)

# Define an array of elements
array = np.array([3, 6, 9])

# Find the LCM of the array using reduce() and lcm()
lcm_array = functools.reduce(lcm, array)

# Find the GCD of the array using reduce() and numpy.gcd()
gcd_array = functools.reduce(np.gcd, array)

# Print the array and the results of the LCM and GCD
print("Array:", array)
print("LCM:", lcm_array)
print("GCD:", gcd_array)

Array: [3 6 9]
LCM: 18
GCD: 3
