Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)

In [11]:
import numpy as np

# Create two 3x3 matrices with random values
matrix1 = np.random.randint(10, size=(3, 3))
matrix2 = np.random.randint(5, size=(3, 3))

# Calculate the product of the elements in the matrices
product = np.prod(matrix1)

# Perform matrix multiplication
multiplication = np.matmul(matrix1, matrix2)

# Perform dot product
dot_product = np.dot(matrix1, matrix2)

# Print the matrices and the results of the operations
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nProduct of elements in Matrix 1:", product)
print("\nMatrix multiplication:\n", multiplication)
print("\nDot product:\n", dot_product)

Matrix 1:
 [[9 5 6]
 [4 9 7]
 [4 8 3]]

Matrix 2:
 [[0 3 0]
 [4 0 4]
 [3 0 4]]

Product of elements in Matrix 1: 6531840

Matrix multiplication:
 [[38 27 44]
 [57 12 64]
 [41 12 44]]

Dot product:
 [[38 27 44]
 [57 12 64]
 [41 12 44]]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR

In [22]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Perform set operations
union = np.union1d(array1, array2)
intersection = np.intersect1d(array1, array2)
set_difference = np.setdiff1d(array1, array2)
xor = np.setxor1d(array1, array2)

# Print the results
print("Array 1:", array1)
print("Array 2:", array2)
print("Union:", union)
print("Intersection:", intersection)
print("Set difference (Array 1 - Array 2):", set_difference)
print("XOR:", xor)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Union: [1 2 3 4 5 6 7 8]
Intersection: [4 5]
Set difference (Array 1 - Array 2): [1 2 3]
XOR: [1 2 3 6 7 8]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array

In [15]:
import numpy as np

# Create a 1D array with random values
array = np.random.randint(10, size=(5))

# Calculate the cumulative sum of the elements in the array
cumulative_sum = np.cumsum(array)

# Calculate the cumulative product of the elements in the array
cumulative_product = np.cumprod(array)

# Calculate the discrete difference of the elements in the array with n=3
discrete_diff = np.diff(array, n=3)

# Find the unique elements in the array
unique_elements = np.unique(array)

# Print the array and the results of the operations
print("Array:", array)
print("\nCumulative sum:", cumulative_sum)
print("\nCumulative product:", cumulative_product)
print("\nDiscrete difference (n=3):", discrete_diff)
print("\nUnique elements:", unique_elements)

Array: [6 3 1 2 0]

Cumulative sum: [ 6  9 10 12 12]

Cumulative product: [ 6 18 18 36  0]

Discrete difference (n=3): [ 2 -6]

Unique elements: [0 1 2 3 6]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [17]:
import numpy as np

# Create two 1D arrays with random values
array1 = np.random.randint(5, size=(5))
array2 = np.random.randint(5, size=(5))

# Perform addition using zip() and list comprehension
zip_addition = np.array([x + y for x, y in zip(array1, array2)])

# Perform addition using numpy.add()
numpy_addition = np.add(array1, array2)

# Create a user-defined function for addition
def add(x, y):
    return x + y

# Create a ufunc from the user-defined function
ufunc_add = np.frompyfunc(add, 2, 1)

# Perform addition using the ufunc
ufunc_addition = ufunc_add(array1, array2)

# Print the arrays and the results of the addition
print("Array 1:", array1)
print("\nArray 2:", array2)
print("\nAddition using zip() and list comprehension:", zip_addition)
print("\nAddition using numpy.add():", numpy_addition)
print("\nAddition using ufunc:", ufunc_addition)

Array 1: [4 4 4 3 1]

Array 2: [3 2 3 4 0]

Addition using zip() and list comprehension: [7 6 7 7 1]

Addition using numpy.add(): [7 6 7 7 1]

Addition using ufunc: [7 6 7 7 1]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [19]:
import numpy as np
import functools

# Define a function to calculate the LCM of two numbers
def lcm(a, b):
    return (a * b) // np.gcd(a, b)

# Define an array of elements
array = np.array([3, 6, 9])

# Find the LCM of the array using reduce() and lcm()
lcm_array = functools.reduce(lcm, array)

# Find the GCD of the array using reduce() and numpy.gcd()
gcd_array = functools.reduce(np.gcd, array)

# Print the array and the results of the LCM and GCD
print("Array:", array)
print("LCM:", lcm_array)
print("GCD:", gcd_array)

Array: [3 6 9]
LCM: 18
GCD: 3
