Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [18]:
import numpy as np

# Array indexing
arr = np.array([1, 2, 3, 4, 5])
print("Array Indexing:")
print("Original array:", arr)
print("Single element at index 2:", arr[2])
print("Multiple elements at indices 1 and 3:", arr[[1, 4]])

# Fancy indexing
print("\nFancy Indexing:")
print("Original array:", arr)
print("Multiple elements at indices 1 and 3:", arr[np.array([1, 4])])

Array Indexing:
Original array: [1 2 3 4 5]
Single element at index 2: 3
Multiple elements at indices 1 and 3: [2 5]

Fancy Indexing:
Original array: [1 2 3 4 5]
Multiple elements at indices 1 and 3: [2 5]


Q2. Execute the 2D array Slicing.

In [17]:
import numpy as np

# Create a 2D array
arr = np.array([[3, 5, 7, 9, 11], [2, 4, 6, 8, 10]])
print("Original array:")
print(arr)

# Slicing a 2D array
arr_slice = arr[1:, 1:3]
print("\nSliced array:")
print(arr_slice)

Original array:
[[ 3  5  7  9 11]
 [ 2  4  6  8 10]]

Sliced array:
[[4 6]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [16]:
import numpy as np

# Create a 5D array using ndmin
arr = np.array([1, 2, 3, 4, 5], ndmin=5)

# Print the array and its shape
print("5D array:")
print(arr)
print("Shape of the array:", arr.shape)

5D array:
[[[[[1 2 3 4 5]]]]]
Shape of the array: (1, 1, 1, 1, 5)


Q4. Reshape the array from 1-D to 2-D array.

In [15]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the array to a 2D array
arr_2d = arr.reshape(2, 4)

# Print the original and reshaped arrays
print("Original array:")
print(arr)
print("\n")
print("Reshaped array:")
print(arr_2d)

Original array:
[1 2 3 4 5 6 7 8]


Reshaped array:
[[1 2 3 4]
 [5 6 7 8]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [13]:
import numpy as np

# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack the arrays vertically
vstacked = np.vstack((arr1, arr2))
print("Vertical Stack:")
print(vstacked)
print("\n")

# Stack the arrays horizontally
hstacked = np.hstack((arr1, arr2))
print("Horizontal Stack:")
print(hstacked)
print("\n")

# Create two 2D arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack the arrays depth-wise
dstacked = np.dstack((arr3, arr4))
print("Depth-wise Stack:")
print(dstacked)

Vertical Stack:
[[1 2 3]
 [4 5 6]]


Horizontal Stack:
[1 2 3 4 5 6]


Depth-wise Stack:
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


Q6. Perform the searchsort method in Numpy array.

In [11]:
import numpy as np

# Create a sorted 1D array
arr = np.array([1, 3, 5, 7, 9])

# Search for elements in the array
print("Array:", arr)
print("Index of 4 using left side:", np.searchsorted(arr, 4, side='left'))
print("Index of 4 using right side:", np.searchsorted(arr, 4, side='right'))
print("Index of 6 using left side:", np.searchsorted(arr, 6, side='left'))
print("Index of 6 using right side:", np.searchsorted(arr, 6, side='right'))

Array: [1 3 5 7 9]
Index of 4 using left side: 2
Index of 4 using right side: 2
Index of 6 using left side: 3
Index of 6 using right side: 3


Q7. Create Numpy Structured array using your domain features.

In [10]:
import numpy as np

# Create a structured array with two fields
data = np.array([(1, "John", 25), (2, "Jane", 30)], dtype=[("id", int), ("name", "U10"), ("age", int)])

# Print the structured array
print(data)

[(1, 'John', 25) (2, 'Jane', 30)]


Q8. Create Data frame using List and Dictionary.

In [9]:
import pandas as pd

# Create a list of lists
data = [[1, "John", 25], [2, "Jane", 30], [3, "Bob", 35]]

# Create a DataFrame from the list of lists
df = pd.DataFrame(data, columns=["id", "name", "age"])

# Print the DataFrame
print(df)
print("\n")


# Create a list of dictionaries
data = [{"id": 1, "name": "John", "age": 25},
        {"id": 2, "name": "Jane", "age": 30},
        {"id": 3, "name": "Bob", "age": 35}]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

   id  name  age
0   1  John   25
1   2  Jane   30
2   3   Bob   35


   id  name  age
0   1  John   25
1   2  Jane   30
2   3   Bob   35


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [24]:
import pandas as pd
import numpy as np

# Create a list of dictionaries
data = [{"destination": "Tokyo", "rating": 4.5, "visitors": 100000},
        {"destination": "Kyoto", "rating": 4.2, "visitors": 80000},
        {"destination": "Osaka", "rating": 4.0, "visitors": 70000},
        {"destination": "Hokkaido", "rating": 4.3, "visitors": 60000},
        {"destination": "Okinawa", "rating": 4.1, "visitors": None}]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Print the DataFrame
print(df)
print("\n")


# Check for missing values
print("Missing values:")
print(df.isnull())
print("\n")


# Check for non-missing values
print("Non-missing values:")
print(df.notnull())
print("\n")


# Drop rows with missing values
df_dropped = df.dropna()
print("Dropped missing values:")
print(df_dropped)
print("\n")


# Fill missing values with a specified value
df_filled = df.fillna(0)
print("Filled missing values:")
print(df_filled)
print("\n")


# Replace missing values with a specified value
df_replaced = df.replace(np.nan, 'Unknown')
print("Replaced missing values:")
print(df_replaced)
print("\n")


# Interpolate missing values using a linear method
df_interpolated = df.interpolate()
print("Interpolated missing values:")
print(df_interpolated)

  destination  rating  visitors
0       Tokyo     4.5  100000.0
1       Kyoto     4.2   80000.0
2       Osaka     4.0   70000.0
3    Hokkaido     4.3   60000.0
4     Okinawa     4.1       NaN


Missing values:
   destination  rating  visitors
0        False   False     False
1        False   False     False
2        False   False     False
3        False   False     False
4        False   False      True


Non-missing values:
   destination  rating  visitors
0         True    True      True
1         True    True      True
2         True    True      True
3         True    True      True
4         True    True     False


Dropped missing values:
  destination  rating  visitors
0       Tokyo     4.5  100000.0
1       Kyoto     4.2   80000.0
2       Osaka     4.0   70000.0
3    Hokkaido     4.3   60000.0


Filled missing values:
  destination  rating  visitors
0       Tokyo     4.5  100000.0
1       Kyoto     4.2   80000.0
2       Osaka     4.0   70000.0
3    Hokkaido     4.3   60000.0
4

Q10. Perform the Hierarchical Indexing in the above created dataset.

In [3]:

import pandas as pd

# Create a DataFrame
data = {
    'Country': ['USA', 'USA', 'Canada', 'Canada', 'Mexico', 'Mexico'],
    'City': ['New York', 'Los Angeles', 'Toronto', 'Vancouver', 'Mexico City', 'Cancun'],
    'Population': [8.4, 3.9, 2.9, 2.5, 8.9, 0.7]
}

df = pd.DataFrame(data)

# Perform hierarchical indexing
df.set_index(['Country', 'City'], inplace=True)

print(df)


print(df.loc['USA'])

                     Population
Country City                   
USA     New York            8.4
        Los Angeles         3.9
Canada  Toronto             2.9
        Vancouver           2.5
Mexico  Mexico City         8.9
        Cancun              0.7
             Population
City                   
New York            8.4
Los Angeles         3.9
